[phases.setup]
nixPkgs = ["python3", "nodejs"]

[phases.install]
cmds = [
  "python3 -m pip install --upgrade pip",
  "python3 -m pip install -r server/requirements.txt",
  "cd client && npm install",
]

[phases.build]
cmds = ["cd client && npm run build"]

[start]
cmd = "cd server && uvicorn main:app --host 0.0.0.0 --port $PORT"
